apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secrets-manager
  namespace: default
subjects:
- kind: Group
  name: secrets-manager
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: secrets-manager
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secrets-viewer
  namespace: default
subjects:
- kind: Group
  name: secrets-viewer
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: secrets-viewer
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-resources-viewer
subjects:
- kind: Group
  name: cluster-resources-viewer
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-resources-viewer
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-resources-manager
subjects:
- kind: Group
  name: cluster-resources-manager
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-resources-manager
  apiGroup: rbac.authorization.k8s.io
